### ISSUE TITLE
convolution segmentation fault

### ISSUE THREAD

**Issue by johnjmolina** [dealias/fftwpp#1]
I run into segmentation faults when running the tests (conv2 and conv3, all others seem ok).

I'm using clang, and to get convolution.cc to compile (non-POD variable-length arrays are not suported), I modified ImplicitHConvolution::convolve as follows

```c++
void ImplicitHConvolution::convolve(Complex **F, 
                                    realmultiplier *pmult, unsigned int offset)

475- Complex c1c[C] ;
475+ Complex * c1c = new Complex[C];
...
515- Complex S[B];
515+ Complex * S = new Complex[B]
...

601+ delete[] c1c;
602+ delete[] S;
```

The tests (conv2/conv3) give a segmentation fault when running 
```c++
void ImplicitConvolution::convolve(Complex **F,
                                   multiplier *pmult, unsigned int offset)
```
at the point where premult is called (more specifically at line 249)
```c++
213 void ImplicitHConvolution::premult(Complex ** F,
				   unsigned int offset,
				   Complex* f1c){
...
if(even) {
   ...
    for(unsigned int i=0; i < A; ++i) {
     ...
249      STORE(f1c+i,CONJ(A+B)); //segmentation fault
    }
  }
}
```
I haven't tested with any other compilers.  I was wondering if this is due to the changes I made, a clang issue, or something else? 
Thanks for the help.

Just in case, this is the output
```
$ ./conv2
min padded buffer=10
min padded buffer=10
nx=16, ny=16
mx=4, my=4
N=39062
threads=1

Segmentation fault: 11

$ ./conv3
min padded buffer=10
min padded buffer=10
min padded buffer=10
nx=16, ny=16, nz=16
mx=4, my=4, mz=4
N=2441
threads=1

Segmentation fault: 11
```

**Comment by johncbowman** [comment]
Sorry for taking so long to look into this. Your changes would normally have been okay, but the c1c vector needs to be 16-byte aligned since it gets passed to routines that use SSE2 vector instructions. This fix is now in the indivisible branch which will be merged into the master branch in a day or two. Thanks for pointing this out! I tested clang on the indivisible branch and conv2 works perfectly.

diff --git a/convolution.cc b/convolution.cc
index 7ae091c..7baf4e3 100644
--- a/convolution.cc
+++ b/convolution.cc
@@ -472,7 +472,7 @@ void ImplicitHConvolution::convolve(Complex **F,
   // Set problem-size variables and pointers:
 
   unsigned int C=max(A,B);
-  Complex c1c[C];
+  Complex *c1c=ComplexAlign(C);
 
   Complex *C0[A], *C1[A], *c2[A]; // inputs to complex2real FFTs
   double  *D0[A], *D1[A]; // outputs of complex2real FFTs
@@ -512,7 +512,7 @@ void ImplicitHConvolution::convolve(Complex **F,
 
 
   // Complex-to-real FFTs and pmults:
-  Complex S[B];
+  Complex *S=new Complex[B];
   {
     // r=2:
     for(unsigned int i=0; i < A; ++i)
@@ -597,6 +597,8 @@ void ImplicitHConvolution::convolve(Complex **F,
     }
     postmultadd0(c2,c0,c1c);
   }
+  delete[] S;
+  deleteAlign(c1c);
 }
