### ISSUE TITLE
fftwpp cann't obtain correct results for the 2D Poisson problem , Could you please help me out.

### ISSUE THREAD

**Issue by ztdepztdep** [dealias/fftwpp#23]
![image](https://user-images.githubusercontent.com/8356693/191223548-f71889f4-42ed-46d7-aea0-d5650ab493ad.png)
I cann't find the error in my program. 
May be the storage sequence of the discrete f^ coefficients  are different from the natural order in a rectangular region?
does the f^ coefficients orderd in the following way:
[-N/2, -N/2+1.....0..1,2,3......N/2-1  ]?

**Comment by johncbowman** [comment]
Since your field is real, it's Fourier transform is Hermitian symmetric. The example you should follow is example2r.cc
in the examples directory. This example uses rcfft2d, which is documented in fftw++.h:

```
// Compute the complex two-dimensional Fourier transform of nx times ny real
// values, using phase sign -1.
// Before calling fft(), the array in must be allocated as double[nx*ny] and
// the array out must be allocated as Complex[nx*(ny/2+1)]. The arrays in
// and out may coincide, allocated as Complex[nx*(ny/2+1)].
//
// Out-of-place usage:
//
//   rcfft2d Forward(nx,ny,in,out);
//   Forward.fft(in,out);       // Origin of Fourier domain at (0,0)
//   Forward.fft0(in,out);      // Origin of Fourier domain at (nx/2,0);
//                                 input destroyed.
//
// In-place usage:
//
//   rcfft2d Forward(nx,ny);
//   Forward.fft(in);           // Origin of Fourier domain at (0,0)
//   Forward.fft0(in);          // Origin of Fourier domain at (nx/2,0)
//
// Notes:
//   in contains the nx*ny real values stored as a Complex array;
//   out contains the upper-half portion (ky >= 0) of the Complex transform.

```
So if you call fft0, the output will be ordered as you suggested in the x direction. But in the y direction only the non-negative frequencies are generated (the negative frequencies can be obtained by Hermitian symmetry).
